#undef OP_EXIT
#undef OP_PUSH
#undef OP_POP
#undef OP_DEFUN
#undef OP_SET
#undef OP_GOTO
#undef OP_RELATIVE
#undef OP_RTS
#undef OP_JSR
#undef OP_IF
#undef OP_ENDIF
#undef OP_ELSE
#undef OP_THEN
#undef OP_LAST
#undef OP_INVALID
#undef EQUAL
#undef PLUS
#undef MINUS
#undef DIV
#undef MULT
#undef INF
#undef LAST